### PR TITLE
Add authorizedMint and whitelist Reservoir Relay EOA

### PR DESCRIPTION
**Pull request by channing-magiceden**
- Add `authorizedMint` in 1155 and 721
- Whitelisted Reservoir Relay EOA by default

### CODE REVIEW

**Comment by tenthirtyone** [comment]
If that EOA is compromised or the relationship with the EOA changes I'm not seeing any protections that can ever remove it. I think the `_authorizedMinters` mapping needs add/remove methods and a process for managing access to those functions.

What is the motivation for setting the EoA as a constant if it can be passed as a constructor param?

**Comment by channing-magiceden** [comment]
> If that EOA is compromised or the relationship with the EOA changes I'm not seeing any protections that can ever remove it. I think the `_authorizedMinters` mapping needs add/remove methods and a process for managing access to those functions.
> 
> What is the motivation for setting the EoA as a constant if it can be passed as a constructor param?

Good suggestion. My initial intention is to make Reservior Relay fixed so it cannot be modified. But after some thoughts I think it's  better to make the list mutable (by owner only).

**Comment by tenthirtyone** [comment]
Should work. 

In the future what do you think about something like `AuthorizedMinter.sol` and inherit/extend but it's not necessary in this PR, I think.

**Review by tenthirtyone — APPROVED** [review]
See comments about `AuthorizedMinter.sol` in the future. There could probably be some zero address checks but it should be benign/caught by the underlying standard.

**Comment by channing-magiceden** [comment]
> Should work.
> 
> In the future what do you think about something like `AuthorizedMinter.sol` and inherit/extend but it's not necessary in this PR, I think.

I think we could switch to use OZ's Access Control / `Role` to consolidate `owner` and `authorizer`.

**Comment by nothing0012** [comment]
worth refactoring later, but yeah, lgtm for now, that we delay the introduction of another Roles dependency

**Pull request merged**
